# Generated by Django 5.0.1 on 2024-06-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='picked_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_time',
            field=models.CharField(choices=[('8 A.M. to 9 A.M.', '8 A.M. to 9 A.M.'), ('9 A.M. to 10 A.M.', '9 A.M. to 10 A.M.'), ('10 A.M. to 11 A.M.', '10 A.M. to 11 A.M.'), ('11 A.M. to 12 P.M.', '11 A.M. to 12 P.M.'), ('12 P.M. to 1 P.M.', '12 P.M. to 1 P.M.'), ('2 P.M. to 3 P.M.', '2 P.M. to 3 P.M.'), ('3 P.M. to 4 P.M.', '3 P.M. to 4 P.M.')], default='8 A.M. to 9 A.M.', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('ready for pick up', 'Ready for pickup'), ('transaction complete', 'Transaction completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
